import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  containerApp: {
    flex: 1,
    flexDirection: 'column',
    justifyContent: 'space-around',
    backgroundColor: '#8fbc8f',
    alignItems: 'stretch',
  },
  meioTela: {
    height: '25%',
    width: '100%',
    marginTop: '30%',
  },
  meioTela2: {
    height: '25%',
    width: '100%',
    marginBottom: '50%',
  },
  listaPlantas: {
    backgroundColor: 'white',
    width: '80%',
    height: '90%',
    marginLeft: '10%',
    borderRadius: 10,
    shadowColor: 'black',
    shadowOffset: { width: -2, height: 4 },
    shadowOpacity: 0.5,
    shadowRadius: 3,
  },
  leitorQrCod: {
    backgroundColor: 'white',
    width: '80%',
    height: '90%',
    marginLeft: '10%',
    borderRadius: 10,
    shadowColor: 'black',
    shadowOffset: { width: -2, height: 4 },
    shadowOpacity: 0.5,
    shadowRadius: 3,
  },
  topoDaTela: {
    backgroundColor: 'white',
    width: '85%',
    height: '13%',
    marginLeft: '8%',
    borderRadius: 10,
    marginTop: '20%',
    shadowColor: 'black',
    shadowOffset: { width: -2, height: 4 },
    shadowOpacity: 0.5,
    shadowRadius: 3,
  },
  divBotoes: {
    height: '100%',
    flexDirection: 'row',
    alignItems: 'center',
  },
  titulo: {
    fontSize: 25,
    marginLeft: '30%',
    marginTop: '10%',
  },
  arrow: {
    width: '20%',
    height: '105%',
    marginLeft: '5%',
    marginTop: '-12%',
  },
  qrCode: {
    width: '20%',
    height: '40%',
    marginLeft: '5%',
    marginRight: '10%',
  },
  listIcon: {
    width: '20%',
    height: '40%',
    marginLeft: '5%',
    marginRight: '10%',
  },
});
